"""
train.py

Main training entry point for HLI-01 v1.0.0.

Provides a reusable training pipeline that can be called
directly or by the research experiment runner.
"""

from pathlib import Path
import random

import numpy as np
import torch

from src.config.settings import (
    DATASET_PATH,
    NUM_CLASSES,
    NUM_EPOCHS,
    LEARNING_RATE,
    RANDOM_SEED,
    INPUT_SIZE,
    HIDDEN_SIZE,
    NUM_LAYERS,
    LR_SCHEDULER_FACTOR,
    LR_SCHEDULER_PATIENCE,
    FIGURE_DIR,
)

from src.models.lstm_model import LSTMModel
from src.training.data_loader import DataLoaderManager
from src.training.trainer import Trainer
from src.training.checkpoint_manager import CheckpointManager
from src.evaluation.evaluator import Evaluator
from src.dataset.dataset_collector import DatasetCollector
from src.visualization.confusion_matrix_plot import ConfusionMatrixPlotter
from experiments.prediction_logger import PredictionLogger
from src.visualization import TrainingPlotter


def set_random_seed(seed):
    """
    Configure random seeds for reproducible training.
    """

    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)

    if torch.cuda.is_available():
        torch.cuda.manual_seed(seed)
        torch.cuda.manual_seed_all(seed)


def run_training(
    checkpoint_dir="outputs/checkpoints",
    figure_dir=None,
    seed=RANDOM_SEED,
    epochs=NUM_EPOCHS,
):
    """
    Run the complete HLI-01 training pipeline.

    Parameters
    ----------
    checkpoint_dir : str or Path
        Directory where model checkpoints are stored.

    figure_dir : str or Path, optional
        Directory where training figures are stored.
        If omitted, the centralized FIGURE_DIR is used.

    seed : int
        Random seed used for reproducibility.

    epochs : int
        Maximum number of training epochs.

    Returns
    -------
    history : dict
        Training history generated by Trainer.

    summary : dict
        Serializable summary of the training run.
    """

    if figure_dir is None:
        figure_dir = FIGURE_DIR

    checkpoint_dir = Path(checkpoint_dir)
    figure_dir = Path(figure_dir)

    checkpoint_dir.mkdir(
        parents=True,
        exist_ok=True,
    )

    figure_dir.mkdir(
        parents=True,
        exist_ok=True,
    )

    print("=" * 60)
    print("HLI-01 v1.0.0 - Training Pipeline")
    print("=" * 60)

    # --------------------------------------------------
    # Reproducibility
    # --------------------------------------------------

    set_random_seed(seed)

    print()
    print(
        "Random seed       :",
        seed,
    )

    # --------------------------------------------------
    # Device
    # --------------------------------------------------

    device = torch.device(
        "cuda"
        if torch.cuda.is_available()
        else "cpu"
    )

    print(
        "Device            :",
        device,
    )

    # --------------------------------------------------
    # Configuration summary
    # --------------------------------------------------

    print()
    print("=" * 60)
    print("Training Configuration")
    print("=" * 60)

    print(
        "Input size        :",
        INPUT_SIZE,
    )

    print(
        "Hidden size       :",
        HIDDEN_SIZE,
    )

    print(
        "LSTM layers       :",
        NUM_LAYERS,
    )

    print(
        "Number of classes :",
        NUM_CLASSES,
    )

    print(
        "Maximum epochs    :",
        epochs,
    )

    print(
        "Learning rate     :",
        LEARNING_RATE,
    )

    print(
        "Scheduler factor  :",
        LR_SCHEDULER_FACTOR,
    )

    print(
        "Scheduler patience:",
        LR_SCHEDULER_PATIENCE,
    )

    # --------------------------------------------------
    # Dataset
    # --------------------------------------------------

    print()
    print("=" * 60)
    print("Loading Dataset")
    print("=" * 60)

    data_manager = DataLoaderManager()

    (
        train_loader,
        valid_loader,
        test_loader,
    ) = data_manager.create()

    print()
    print(
        "Training batches  :",
        len(train_loader),
    )

    print(
        "Validation batches:",
        len(valid_loader),
    )

    print(
        "Testing batches   :",
        len(test_loader),
    )

    # --------------------------------------------------
    # Model
    # --------------------------------------------------

    print()
    print("=" * 60)
    print("Creating Model")
    print("=" * 60)

    model = LSTMModel(
        input_size=INPUT_SIZE,
        hidden_size=HIDDEN_SIZE,
        num_layers=NUM_LAYERS,
        num_classes=NUM_CLASSES,
    )

    model = model.to(device)

    print()
    print("Model created successfully.")

    # --------------------------------------------------
    # Optimizer
    # --------------------------------------------------

    optimizer = torch.optim.Adam(
        model.parameters(),
        lr=LEARNING_RATE,
    )

    # --------------------------------------------------
    # Learning-rate scheduler
    # --------------------------------------------------

    scheduler = (
        torch.optim.lr_scheduler.ReduceLROnPlateau(
            optimizer,
            mode="min",
            factor=LR_SCHEDULER_FACTOR,
            patience=LR_SCHEDULER_PATIENCE,
        )
    )

    # --------------------------------------------------
    # Trainer
    # --------------------------------------------------

    trainer = Trainer(
        model=model,
        train_loader=train_loader,
        valid_loader=valid_loader,
        optimizer=optimizer,
        device=device,
        epochs=epochs,
        scheduler=scheduler,
        checkpoint_dir=checkpoint_dir,
    )

    # --------------------------------------------------
    # Training
    # --------------------------------------------------

    print()
    print("=" * 60)
    print("Starting Training")
    print("=" * 60)

    history = trainer.train()

    # --------------------------------------------------
    # Training summary
    # --------------------------------------------------

    print()
    print("=" * 60)
    print("Training Complete")
    print("=" * 60)

    print()

    print(
        "Best epoch          :",
        trainer.best_epoch,
    )

    print(
        "Best validation loss:",
        f"{trainer.best_loss:.4f}",
    )

    print(
        "Epochs completed    :",
        len(history["train_loss"]),
    )

    final_lr = optimizer.param_groups[0]["lr"]

    print(
        "Final learning rate :",
        f"{final_lr:.6f}",
    )

    # --------------------------------------------------
    # Training visualizations
    # --------------------------------------------------

    print()
    print("=" * 60)
    print("Generating Training Visualizations")
    print("=" * 60)

    plotter = TrainingPlotter(
        save_dir=figure_dir
    )

    plot_outputs = plotter.plot_history(
        history
    )

    print()

    if "loss" in plot_outputs:
        print(
            "Loss curve         :",
            plot_outputs["loss"],
        )

    if "accuracy" in plot_outputs:
        print(
            "Accuracy curve     :",
            plot_outputs["accuracy"],
        )

    if "learning_rate" in plot_outputs:
        print(
            "Learning-rate curve:",
            plot_outputs["learning_rate"],
        )

    # --------------------------------------------------
    # Outputs
    # --------------------------------------------------

    checkpoint_path = (
        checkpoint_dir / "best_model.pth"
    )

    print()
    print("=" * 60)
    print("Training Outputs")
    print("=" * 60)

    print()
    print("Best checkpoint:")
    print(checkpoint_path)

    print()
    print("Training figures:")

    for output_path in plot_outputs.values():
        print(output_path)

    # --------------------------------------------------
    # Test-set evaluation
    # --------------------------------------------------

    print()
    print("=" * 60)
    print("Evaluating Best Model on Test Set")
    print("=" * 60)

    checkpoint_manager = CheckpointManager(
        checkpoint_dir=checkpoint_dir
    )

    checkpoint_manager.load_model(
        model=model,
        filename="best_model.pth",
        device=device,
    )

    model = model.to(device)
    model.eval()

    y_true = []
    y_pred = []
    prediction_records = []
    sample_index = 0

    with torch.no_grad():

        for inputs, labels in test_loader:

            inputs = inputs.to(device)
            labels = labels.to(device)

            outputs = model(inputs)

            probabilities = torch.softmax(
                outputs,
                dim=1,
            )

            confidences, predictions = torch.max(
                probabilities,
                dim=1,
            )

            batch_true = labels.cpu().tolist()
            batch_pred = predictions.cpu().tolist()
            batch_confidence = confidences.cpu().tolist()

            y_true.extend(batch_true)
            y_pred.extend(batch_pred)

            for true_id, pred_id, confidence in zip(
                batch_true,
                batch_pred,
                batch_confidence,
            ):
                prediction_records.append(
                    {
                        "sample_index": sample_index,
                        "ground_truth_id": true_id,
                        "prediction_id": pred_id,
                        "confidence": float(confidence),
                        "correct": true_id == pred_id,
                    }
                )

                sample_index += 1

    evaluation = Evaluator.evaluate(
        y_true,
        y_pred,
    )

    test_accuracy = float(
        evaluation["accuracy"]
    )

    test_precision = float(
        evaluation["precision"]
    )

    test_recall = float(
        evaluation["recall"]
    )

    test_f1_score = float(
        evaluation["f1_score"]
    )

    test_confusion_matrix = (
        evaluation["confusion_matrix"].tolist()
    )

    print()
    print(
        "Test Accuracy      :",
        f"{test_accuracy:.4f}",
    )

    print(
        "Test Precision     :",
        f"{test_precision:.4f}",
    )

    print(
        "Test Recall        :",
        f"{test_recall:.4f}",
    )

    print(
        "Test F1-score      :",
        f"{test_f1_score:.4f}",
    )

    # --------------------------------------------------
    # Research evaluation artifacts
    # --------------------------------------------------

    class_names = DatasetCollector(
        DATASET_PATH
    ).get_classes()

    for record in prediction_records:
        record["ground_truth_label"] = (
            class_names[
                record["ground_truth_id"]
            ]
        )

        record["prediction_label"] = (
            class_names[
                record["prediction_id"]
            ]
        )

    confusion_plotter = ConfusionMatrixPlotter(
        save_dir=figure_dir
    )

    confusion_matrix_path = confusion_plotter.plot(
        confusion_matrix=test_confusion_matrix,
        class_names=class_names,
        filename="confusion_matrix.png",
    )

    prediction_logger = PredictionLogger(
        experiment_dir=checkpoint_dir.parent
    )

    predictions_path = (
        prediction_logger.save_predictions(
            prediction_records
        )
    )

    print()
    print(
        "Confusion matrix   :",
        confusion_matrix_path,
    )

    print(
        "Predictions CSV    :",
        predictions_path,
    )

    # --------------------------------------------------
    # Serializable training summary
    # --------------------------------------------------

    summary = {
        "best_epoch": trainer.best_epoch,
        "best_validation_loss": float(
            trainer.best_loss
        ),
        "epochs_completed": len(
            history["train_loss"]
        ),
        "final_learning_rate": float(
            final_lr
        ),
        "device": str(device),
        "checkpoint_path": str(
            checkpoint_path
        ),
        "test_accuracy": test_accuracy,
        "test_precision": test_precision,
        "test_recall": test_recall,
        "test_f1_score": test_f1_score,
        "test_confusion_matrix": (
            test_confusion_matrix
        ),
        "confusion_matrix_path": str(
            confusion_matrix_path
        ),
        "predictions_path": str(
            predictions_path
        ),
    }

    # --------------------------------------------------
    # Final status
    # --------------------------------------------------

    print()
    print("=" * 60)
    print(
        "HLI-01 v1.0.0 training "
        "pipeline completed successfully."
    )
    print("=" * 60)

    return history, summary


def main():
    """
    Run HLI-01 training using the standard project outputs.
    """

    run_training()


if __name__ == "__main__":
    main()
